title: Flickrdpf
description: Utilities for a networkable digital picture frame. Grabs pictures from Flickr. Should be considered very beta.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
